### ISSUE TITLE
Capfile require fails

### ISSUE THREAD

**Issue by ain** [netguru/capistrano-docker#1]
Followed the README, but it fails to require:

```
root@a5c29b3891b5:/home/app# cap staging deploy --trace
cap aborted!
LoadError: cannot load such file -- capistrano/docker
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/app/capfile:10:in `<top (required)>'
/usr/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/var/lib/gems/2.2.0/gems/capistrano-3.3.5/lib/capistrano/application.rb:15:in `run'
/var/lib/gems/2.2.0/gems/capistrano-3.3.5/bin/cap:3:in `<top (required)>'
/usr/local/bin/cap:23:in `load'
/usr/local/bin/cap:23:in `<main>'
```

**Comment by rindek** [comment]
Hi @ain thanks for submitting this issue.

I forgot to mention that after adding this to Gemfile you have to run `bundle install` to install this gem, and also you'll have to use cap command with `bundle exec` to load up this gem from Gemfile.

Let me know if it helps.

**Comment by rindek** [comment]
I'm closing this one. Reopen if you stil have issues.
